apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p003-certmanager
  namespace: default
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: platform/cert-manager
    repoURL: 'git@github.com:Sushmithad1606/s-dev.git'
    targetRevision: main
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false