apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: platform
spec:
  destination:
    namespace: platform
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.10
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false