apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p004-loki
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          isDefault: true
          persistence:
            enabled: true
            size: 50Gi

          config:
            memberlist:
              bind_addr:
                - ${MY_POD_IP}
            table_manager:
              retention_deletes_enabled: true
              retention_period: 120h

        promtail:
          enabled: true
          config:
            lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push

        fluent-bit:
          enabled: false

        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: true
              maxLines: 1000
          image:
            tag: 8.3.5

        prometheus:
          enabled: false
          isDefault: false

        filebeat:
          enabled: false
          filebeatConfig:
            filebeat.yml: |
              # logging.level: debug
              filebeat.inputs:
              - type: container
                paths:
                  - /var/log/containers/*.log
                processors:
                - add_kubernetes_metadata:
                    host: ${NODE_NAME}
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"
              output.logstash:
                hosts: ["logstash-loki:5044"]

        logstash:
          enabled: false
          image: grafana/logstash-output-loki
          imageTag: 1.0.1
          filters:
            main: |-
              filter {
                if [kubernetes] {
                  mutate {
                    add_field => {
                      "container_name" => "%{[kubernetes][container][name]}"
                      "namespace" => "%{[kubernetes][namespace]}"
                      "pod" => "%{[kubernetes][pod][name]}"
                    }
                    replace => { "host" => "%{[kubernetes][node][name]}"}
                  }
                }
                mutate {
                  remove_field => ["tags"]
                }
              }
          outputs:
            main: |-
              output {
                loki {
                  url => "http://loki:3100/loki/api/v1/push"
                  #username => "test"
                  #password => "test"
                }
                # stdout { codec => rubydebug }
              }
    repoURL: https://grafana.github.io/helm-charts/
    targetRevision: 2.10.1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false