global:
  domain: argos.kubeace.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    extraTls:
      - hosts:
        - argos.kubeace.com
        # Based on the ingress controller used secret might be optional
        secretName: argos.kubeace.com-tls-01
